"""empty message

Revision ID: a8a694aa5797
Revises: 5aad3bd27279
Create Date: 2019-02-17 15:22:50.602635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a694aa5797'
down_revision = '5aad3bd27279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('episodes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'episodes')
    # ### end Alembic commands ###
